export const COMPOSER_SEND_REQUEST_HEADER_CMD = "COMPOSER_SEND_REQUEST_HEADER_CMD";
export const COMPOSER_SET_REQUEST_HEADER = "COMPOSER_SET_REQUEST_HEADER";
export const COMPOSER_SEND_RESPONSE_TO_MIDDLEWARE = "COMPOSER_SEND_RESPONSE_TO_MIDDLEWARE";

